export * from './remove'
export * from './update'
export * from './viewsSvg'
export * from './CommentsSvg copy'
export * from './LeftArrow'
export * from './RightArrow'
export * from './exit'
export * from './Loading/LoadingSvg'
export * from './Cat/catSvg'
export * from './Cat/catSittingSvg'
export * from './SendSvg'
export * from './writeSvg'
export * from './Close/CloseSvg'
export * from './home'
export * from './search'